print("    ")
print("    ")
print("''''''''''''''''''")
print(" \n  Welcome to SEAP-Fi \n")
print("''''''''''''''''''")
print("    ")
print("    ")
print("  Nigeria's best mobile banking platform  ")
print("    ")
print("  Please select an option:  ")
print("    ")
print("  1. Customer Onboarding  ")
print("  2. Account Opening  ")
print("  3. Deposit to Account  ")
print("  4. Withdrawal from Account  ")
print("  5. Transfer to other Accounts  ")
print("  6. Account Closing  ")
print("  7. View all Transaction  ")
